name : Python CI

on:
  push:
    branches: 
      - main
    
  pull_request:
    branches:
      - mian

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
      
      - name: Compile Python files
        run: python -m compileall .

      - name: Package application
        run: tar -czf my-ci-demo.tar.gz app.py requirements.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-ci-demo-package
          path: my-ci-demo.tar.gz

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/my-ci-demo:${{ github.sha }} \
            -t ghcr.io/${{ github.repository_owner }}/my-ci-demo:latest \
            .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-ci-demo:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/my-ci-demo:latest


      # - name: Run Docker container
      #   run: |
      #     docker run -d --name ci-container my-ci-demo:latest
      #     sleep 5
      #     docker ps
      #     docker logs ci-container
      #     docker stop ci-container
      #     docker rm ci-container

        

